// frontend/src/App.jsx
import { useState } from 'react'

function App() {
  const [file, setFile] = useState(null)
  const [skills, setSkills] = useState([])
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!file) return

    setLoading(true)
    const formData = new FormData()
    formData.append('file', file)

    try {
      const response = await fetch('http://localhost:5000/upload', {
        method: 'POST',
        body: formData,
      })
      const data = await response.json()
      if (data.error) throw new Error(data.error)
      setSkills(data.skills)
    } catch (error) {
      alert(error.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-100 py-8 px-4">
      <div className="max-w-2xl mx-auto bg-white rounded-lg shadow-md p-6">
        <h1 className="text-3xl font-bold text-gray-800 mb-6">AI Resume Skill Extractor</h1>
        
        <form onSubmit={handleSubmit} className="mb-8">
          <div className="flex flex-col space-y-4">
            <input
              type="file"
              onChange={(e) => setFile(e.target.files[0])}
              className="file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
              accept=".pdf,.docx"
            />
            <button
              type="submit"
              disabled={loading}
              className="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700 disabled:bg-gray-400"
            >
              {loading ? 'Processing...' : 'Analyze Resume'}
            </button>
          </div>
        </form>

        {skills.length > 0 && (
          <div>
            <h2 className="text-xl font-semibold mb-4">Extracted Skills:</h2>
            <div className="flex flex-wrap gap-2">
              {skills.map((skill, index) => (
                <span
                  key={index}
                  className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default App

// frontend/src/App.vue
<template>
    <div class="min-h-screen bg-gray-100 py-8 px-4">
      <div class="max-w-2xl mx-auto bg-white rounded-lg shadow-md p-6">
        <h1 class="text-3xl font-bold text-gray-800 mb-6">AI Resume Skill Extractor</h1>
        
        <FileUpload @upload-success="handleUploadSuccess"/>
        
        <div v-if="skills.length" class="mt-8">
          <h2 class="text-xl font-semibold mb-4">Extracted Skills:</h2>
          <div class="flex flex-wrap gap-2">
            <span 
              v-for="(skill, index) in skills" 
              :key="index"
              class="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm"
            >
              {{ skill }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref } from 'vue'
  import FileUpload from './components/FileUpload.vue'
  
  const skills = ref([])
  
  const handleUploadSuccess = (extractedSkills) => {
    skills.value = extractedSkills
  }
  </script>
